
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - migrate
    env_file:
      - .env.local

  migrate:
    build:
      context: .
      dockerfile: db/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env.local

  postgres:
    image: postgres:17
    restart: always
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
